set(PCTOOL_ARCHIVE_RUNTIME "${CMAKE_SOURCE_DIR}/out/archive-runtime" CACHE PATH "Source-built original 7-Zip runtime")
foreach(file 7z.exe 7zFM.exe 7zG.exe 7z.dll 7-zip.dll 7-zip32.dll 7z.sfx 7zCon.sfx 7-zip.chm Lang/zh-cn.txt License.txt)
    if(NOT EXISTS "${PCTOOL_ARCHIVE_RUNTIME}/${file}")
        message(FATAL_ERROR "7-Zip component missing: ${file}. Run scripts/build-7zip.ps1 and scripts/setup-package-tools.ps1 in the VS developer shell.")
    endif()
endforeach()
add_custom_command(TARGET PcTool POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${PCTOOL_ARCHIVE_RUNTIME}" "$<TARGET_FILE_DIR:PcTool>/modules/archive")
install(TARGETS PcTool RUNTIME DESTINATION .)
install(TARGETS PcToolUninstallHelper RUNTIME DESTINATION .)
install(DIRECTORY "${PCTOOL_ARCHIVE_RUNTIME}/" DESTINATION modules/archive)
install(FILES "${CMAKE_SOURCE_DIR}/third_party/ocr/onnxruntime.dll" DESTINATION .)
install(DIRECTORY "${CMAKE_SOURCE_DIR}/third_party/ocr/models/" DESTINATION ocr_models)
install(DIRECTORY "${CMAKE_SOURCE_DIR}/third_party/ocr/licenses/" DESTINATION ocr_licenses)
install(FILES "${CMAKE_SOURCE_DIR}/README.md" DESTINATION .)
# Developer documentation and test reports stay in the source repository.
set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION .)
set(CMAKE_INSTALL_DEBUG_LIBRARIES OFF)
include(InstallRequiredSystemLibraries)
